### ISSUE TITLE
consider using h2 for questions?

### ISSUE THREAD

**Issue by pmz** [xHayden/obsidian-mochi-cards-pro#1]
thank you for this great plugin.
One remark: h1 is good reserved for the title of the note.
Would you consider adding an option to use h2 or h3 for the questions?

**Comment by xHayden** [comment]
It might be a while till this is done but it will probably be included in the next update.

**Comment by xHayden** [comment]
Implemented in https://github.com/xHayden/obsidian-mochi-cards-pro/commit/12d343af52ba15f7eea665c6c5638527e372591e
